project:
  type: book

book:
  search: false
  title: Best Practices
  subtitle: 大学院生のためのワークショップ
  author:
    - name: 柳本和春
      email: yanagimoto@econ.kobe-u.ac.jp
      orcid: 0009-0007-1967-8304
      affiliations:
        - name: 神戸大学
  date: last-modified
  date-format: "最終更新: YYYY年MM月DD日"
  site-url: https://kazuyanagimoto.com/workshop-graduate-2026
  repo-url: https://github.com/kazuyanagimoto/workshop-graduate-2026
  chapters:
    - index.qmd
    - lesson/architecture.qmd
    - lesson/shell.qmd
    - lesson/git.qmd
    - lesson/quarto.qmd
    - lesson/computation-fast.qmd
    - lesson/computation-data.qmd
    - lesson/api.qmd
    - lesson/visualization.qmd
    - lesson/regression.qmd
    - lesson/slides.qmd
    - lesson/literature.qmd
    - lesson/targets.qmd
    - lesson/ai.qmd
  appendices:
    - lesson/dictionary.qmd
    - references.qmd



format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    number-depth: 2
    lightbox: true


freeze: auto
execute:
  warning: false
  message: false
  error: false

bibliography: references.bib
bibliography-style: chicago-author-date
link-citations: true

knitr:
  opts_chunk: 
    fig.align: center
    fig.retina: 3
    fig.width: 8
    fig.height: 3.708
    out.width: 90%
    collapse: true
    dev: svg