project:
  type: book

book:
  title: Best Practices
  subtitle: 大学院生のためのワークショップ
  author:
    - name: 柳本和春
      email: yanagimoto@econ.kobe-u.ac.jp
      orcid: 0009-0007-1967-8304
      affiliations:
        - name: 神戸大学
  date: last-modified
  date-format: "最終更新: YYYY年MM月DD日"
  chapters:
    - index.qmd
    - part: 基礎
      chapters:
        - lesson/git.qmd
        - lesson/computation.qmd
    - part: 可視化
      chapters:
        - lesson/visualization.qmd
        - lesson/slides.qmd
    - part: プロジェクト管理
      chapters:
        - lesson/literature.qmd
        - lesson/targets.qmd
    - part: AI
      chapters:
        - lesson/ai.qmd
  appendices: 
    - references.qmd



format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

freeze: auto
execute:
  warning: false
  message: false
  error: false

bibliography: references.bib
bibliography-style: chicago-author-date