%%{init: {"theme": "neutral", "htmlLabels": false, "flowchart": {"htmlLabels": false, "diagramPadding": 40, "nodeSpacing": 20, "rankSpacing": 30, "padding": 6}}}%%
graph LR
  here_rel>"here_rel"]:::fn
  subgraph tar_data
    did_raw_file(["did_raw_file"]):::filetarget --> did_raw["did_raw"]:::regular
    did_raw --> did["did"]:::regular
    clean_did>"clean_did"]:::fn --> did
  end
  subgraph tar_analysis
    summarize_did>"summarize_did"]:::fn --> tab_balance["tab_balance"]:::regular
    summarize_trends>"summarize_trends"]:::fn --> trends["trends"]:::regular
    estimate_did>"estimate_did"]:::fn --> models_did["models_did"]:::regular
    estimate_event>"estimate_event"]:::fn --> model_event["model_event"]:::regular
  end
  subgraph tar_manuscript
    manuscript(["manuscript"]):::filetarget
  end
  here_rel --> did_raw_file
  did --> tab_balance
  did --> trends
  did --> models_did
  did --> model_event
  tab_balance --> manuscript
  trends --> manuscript
  models_did --> manuscript
  model_event --> manuscript
  style tar_data fill:#FFFFFF00,stroke:#131516;
  style tar_analysis fill:#FFFFFF00,stroke:#131516;
  style tar_manuscript fill:#FFFFFF00,stroke:#131516;
  classDef regular stroke:#107895,stroke-width:2px,color:#107895,fill:#ffffff;
  classDef filetarget stroke:#9a2515,stroke-width:2px,color:#9a2515,fill:#ffffff;
  classDef fn stroke:#131516,stroke-width:2px,color:#131516,fill:#ffffff;
